version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.19
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - local-network

  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: npm run start
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  data:
    driver: local
