version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5.0.19
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - local-network

  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/api-clean-nodejs
    volumes:
      - ./build/:/usr/src/clean-node-api/build/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5000:5000"
      # - "9222:9222"
    depends_on:
      - mongo
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  data:
    driver: local
