version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    volumes:
      - ./build:/usr/src/clean-node-api/build
    ports:
      - "5000:5000"
    links:
      - mongo
    command: npm start
